export const projects = [
  {
    id: 6,
    name: "NPM counter",
    description: "Get count of any npm package quicky!",
    github: "https://github.com/nishchay17/npmcounter",
    live: "https://npmcounter.vercel.app/",
    tag: "Next, Tailwind, Typescript",
    image: "npm.png",
    createdOn: "2024",
    additionalTags: ["New"],
  },
  {
    id: 5,
    name: "Dev Planet Blog",
    description:
      "Collaborate with Team with team collab. Assign and monitor tasks and share files with the team.",
    github: "https://github.com/nishchay17/planet-blog",
    live: "https://planet-blog.vercel.app/",
    tag: "Next, Tailwind, Typescript, Next auth, Contentlayer, MDX",
    image: "blog.png",
    createdOn: "2023",
    additionalTags: ["New"],
  },
  {
    id: 1,
    name: "Team Collab",
    description:
      "Collaborate with Team with team collab. Assign and monitor tasks and share files with the team.",
    github: "https://github.com/nishchay17/teams-frontend-v2",
    live: "https://teams-frontend.vercel.app/",
    tag: "Next, Tailwind, Node, MongoDB, Express",
    image: "team-collab.png",
    createdOn: "2023",
  },
  {
    id: 3,
    name: "Url Shortener",
    description:
      "Used shrtco.de's API to shorten the given URL and persisted in the local storage.",
    github: "https://github.com/nishchay17/Shortly",
    live: "https://shortlytif.netlify.app/",
    tag: "React",
    image: "url.png",
    createdOn: "2019",
    additionalTags: ["No longer supported"],
  },
  {
    id: 4,
    name: "CDF (CLI)",
    description:
      "Generate files with boilerplate code, for competitive programmers. 1000+ Downloads on NPM.",
    github: "https://github.com/nishchay17/dirMaker",
    live: "https://www.npmjs.com/package/@nishchay17/cdf",
    tag: "Node, CLI",
    image: "cdn.png",
    createdOn: "2020",
  },
  {
    id: 2,
    name: "E-commerce",
    description:
      "E-commerce website for selling t-shirt complete with payment options, with a simple UI.",
    github: "https://github.com/nishchay17/TeeStoreFrontend",
    live: "https://theteestore.netlify.app/",
    tag: "React, Node, MongoDB, Express",
    image: "tee.png",
    createdOn: "2019",
    additionalTags: ["No longer supported"],
  },
];
